{% set name = "fair" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c654b68d94e89a8cfff25081476c91e065d75b9635bc7b67af4843fbfa89728

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pooch
    - scipy
    - tqdm
    - xarray

test:
  requires:
    - python {{ python_min }}
  imports:
    - fair

about:
  home: https://github.com/OMS-NetZero/FAIR
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-amplitude Impulse Response simple climate model.

  description: |
    FaIR (the Finite-amplitude Impulse-Response) climate model is a
    simple climate model, or emulator, useful for producing global
    mean temperature projections from a wide range of emissions or
    prescribed forcing scenarios. 
  dev_url: https://github.com/OMS-NetZero/FAIR

extra:
  recipe-maintainers:
    - bjlittle
    - chrisroadmap
